### ISSUE TITLE
'Timeline' object has no attribute 'has_external'

### ISSUE THREAD

**Issue by vzack2001** [ideoforms/isobar#11]
https://github.com/ideoforms/isobar/blob/44c4b43412e5b596e11ca59794da35ece6b0c13a/isobar/timeline.py#L61

Now it is
if self.has_external.clock:

Maybe
if self.has_external_clock:
?
Thanks :)

**Comment by vzack2001** [comment]
and few line under:
return self.clock_source.bpm
return self.clock.bpm
might be
return self.clock_source
return self.clock

**Comment by ideoforms** [comment]
Thanks, now fixed 👌
