### ISSUE TITLE
Do you know how I might go about implementing the Molecular Music Box algorithm in isobar?

### ISSUE THREAD

**Issue by youssefavx** [ideoforms/isobar#12]
This is what I'm referring to: https://www.youtube.com/watch?v=3Z8CuAC_-bg

Is this simple or difficult to implement in isobar? Would love any help whatsoever. I'm in love with this concept!

**Comment by EnigmaCurry** [comment]
Yes, isobar is a good fit for this, here is my implementation of the molecular music box in isobar : https://github.com/EnigmaCurry/midi-livecode/blob/28d62b9e67d76304fbd16bb198852926b09e4abd/sequences.py - I am still learning isobar (and music math in general) so this might still have a few bugs but its working mainly.

**Comment by youssefavx** [comment]
:o oh my god! I am so excited to try this out, thanks a TON for sharing!

**Comment by youssefavx** [comment]
I keep getting this error, not sure if I'm doing something wrong: 

```
NameError                                 Traceback (most recent call last)
<ipython-input-2-9f12f76b494d> in <module>
     14 midi_out_port = "02. Internal MIDI"
     15 
---> 16 log = logging.getLogger(os.path.basename(__file__))
     17 
     18 def get_midi_output():

NameError: name '__file__' is not defined
```

**Comment by youssefavx** [comment]
This occurs when I run the livecode python file but I run that code in a python notebook. 

Same with sequences: 

```
NameError                                 Traceback (most recent call last)
<ipython-input-1-3fc7d6ee0fef> in <module>
      4 import logging
      5 
----> 6 log = logging.getLogger(os.path.basename(__file__))
      7 
      8 def molecular_music_box(seed, scale=ib.Scale.major, loops=4, bars=4, beats_per_bar = 4, scale_rule=None):

NameError: name '__file__' is not defined
```

**Comment by youssefavx** [comment]
When I run: 

python3 sequences.py

In the terminal, nothing happens. 

When I run: 

python3 livecode.py 

In the terminal, this occurs: 

```
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/josephvanrowe/Documents/midi-livecode/timelines.py", line 24, in main
    molecular_music_box("9A#5", loops=8, bars=4, octave=3, scale=ib.Scale.dorian, bpm=250, delay=True, scale_rule=scale_rule)
  File "/Users/josephvanrowe/Documents/midi-livecode/timelines.py", line 51, in molecular_music_box
    timeline = create_timeline(bpm)
  File "/Users/josephvanrowe/Documents/midi-livecode/livecode.py", line 38, in create_timeline
    output = get_midi_output()
  File "/Users/josephvanrowe/Documents/midi-livecode/livecode.py", line 28, in get_midi_output
    raise RuntimeError("Midi out port not found")
RuntimeError: Midi out port not found
```

I'm not sure how to identify the midi out port

**Comment by youssefavx** [comment]
Never mind! Getting sound now. I set the out port to: 01. Internal Midi, and out to IAC Driver (after checking Ableton).

**Comment by youssefavx** [comment]
One question though: How do I set the note and duration, etc.? Like "4E3"?

**Comment by youssefavx** [comment]
Haha never mind, figured that out as well, edited the timelines python file. Very well done!

**Comment by youssefavx** [comment]
I assume 'loops' refer to the number of generated loops, and 'bars' refers to what would be the loop length (number of beats per loop) here in [this](https://www.tomsnively.com/mmb/) molecular music box? And would that be equal? Meaning a loop length of 32 there would be the same as a bars=32 in your isobar implementation?

**Comment by youssefavx** [comment]
For some reason when I do something like this: 

`molecular_music_box(seed="9C14.5", loops=32, bars=32 scale=ib.Scale.major, octave=3, bpm=120, delay=False, scale_rule=None)`

I briefly get an exact replica of the loop I'm looking for (from the original molecular music box) for a brief moment, but then it just seemingly goes to random notes / timings.

**Comment by EnigmaCurry** [comment]
loops is how many times to record the loop, and bars is the length of that loop (bars=beats*4), the original video only used a four bar loop, so I always set bars=4. If loops=32 you will get very high notes (because the rule is to keep going up), so you might try bars=4, loops=16. if you set delay=True, you will hear the loops build up one-by-one, or with delay=False you will hear all 16 loops start at the same time. 

If you have any other questions, feel free to open an issue on https://github.com/EnigmaCurry/midi-livecode and we can discuss, thanks and good luck :::))

**Comment by youssefavx** [comment]
Thanks so much! Will do!
