### ISSUE TITLE
Installed with pip, example code doesn't work

### ISSUE THREAD

**Issue by muteboy** [ideoforms/isobar#13]
Hi, 
Bit of a noob, so please be kind..
I did "pip install isobar" in the VSCode Terminal on Windows and got the following:
```
Collecting isobar
  Downloading isobar-0.0.1.tar.gz (40 kB)
     |████████████████████████████████| 40 kB 215 kB/s
Collecting python-osc
  Downloading python-osc-1.7.4.tar.gz (23 kB)
Requirement already satisfied: python-rtmidi in c:\users\matthew.petty\appdata\local\programs\python\python36\lib\site-packages (from isobar) (1.4.1)
Collecting midiutil
  Downloading MIDIUtil-1.2.1.tar.gz (1.0 MB)
     |████████████████████████████████| 1.0 MB 198 kB/s
Building wheels for collected packages: isobar, python-osc, midiutil
  Building wheel for isobar (setup.py) ... done
  Created wheel for isobar: filename=isobar-0.0.1-py3-none-any.whl size=39993 sha256=47fc057819579547e9d11d7d58be1fe264e8baab94b650312000260855f9972e
  Stored in directory: c:\users\matthew.petty\appdata\local\pip\cache\wheels\c0\06\72\2e2c2742a309ccb3abe27f5d6b095b682aea77bca07d91d799
  Building wheel for python-osc (setup.py) ... done
  Created wheel for python-osc: filename=python_osc-1.7.4-py3-none-any.whl size=31716 sha256=6c26b461c2453813255321f63e17d5c0bf30745e6a4d4ff61c29f57f709270bc
  Stored in directory: c:\users\matthew.petty\appdata\local\pip\cache\wheels\74\a9\d4\e4888b54ef450d7df4a13f0a70c31295aa9a7656c9995ad071
  Building wheel for midiutil (setup.py) ... done
  Created wheel for midiutil: filename=MIDIUtil-1.2.1-py3-none-any.whl size=55493 sha256=4822101369da83d3552188cafe756b0511b39d37bb752ce1ad530c216b7ce29b
  Stored in directory: c:\users\matthew.petty\appdata\local\pip\cache\wheels\42\09\98\ae0844fcc6f2bbd644cfbd6c04269ce188a43b4bab7e3684d2
Successfully built isobar python-osc midiutil
Installing collected packages: python-osc, midiutil, isobar
Successfully installed isobar-0.0.1 midiutil-1.2.1 python-osc-1.7.4
```

Then I copied and pasted the example program from the README into a new file. It gives the following problems in the editor:

```
Module 'isobar' has no 'PSequence' member
Instance of 'Timeline' has no 'Schedule' member
```

Am I installing it in the correct way? What else could I be doing wrong?

**Comment by ideoforms** [comment]
Thanks for the report! This is because git has fallen out of sync with the latest pip version, and a few of the structure/method names have been amended slightly. I'll push an updated release to PyPi later today which should fix this issue.

**Comment by muteboy** [comment]
OK, thank you! Glad it's not me.

**Comment by ideoforms** [comment]
I've now pushed a new release to PyPi, which should match up with the documentation.
I have also pushed a new set of docs to supplement the simple example in the readme:

https://ideoforms.github.io/isobar/

@muteboy Please do let me know if this fixes the issue. If you have a moment to look through the wider documentation, I'd appreciate any feedback and suggestions, as it's brand new and a fresh pair of eyes on it would be welcomed. Thanks!

**Comment by muteboy** [comment]
Works! Used pip to uninstall, then reinstalled. Copied example, ran it, it plays a piano arpeggio.

I will be sure to check the docs.
