### ISSUE TITLE
Can't hear sounds

### ISSUE THREAD

**Issue by ghost** [ideoforms/isobar#15]
I runned the first example ( also several others) and it says "Opened MIDI output: Midi Through:Midi Through Port-0 14:0". I checked with a midi monitor and it sends a few signals but how can I connect the program to a midi synth on my Ubuntu to hear sounds?

Thanks.

**Comment by hnspn** [comment]
from the docs
> What isobar doesn't do
isobar does not generate any audio on its own. It must be configured to send events to an output device which is responsible for sound synthesis.

you could use vmpk
or fluidsynth
or a DAW like ardour or LMMS
or write your own program that can read midi events and generates sound
