### ISSUE TITLE
scheduling a track on a background timeline - it gets unscheduled immediately

### ISSUE THREAD

**Issue by dtenenba** [ideoforms/isobar#25]
Hi, I was following along with the jupyter notebook in the examples directory, basically running this code:

```python
from isobar import *
import logging
logging.basicConfig(level=logging.INFO)
timeline = Timeline(120)
timeline.background()
stream1 = timeline.schedule()
```

The output of this is:

```
INFO:isobar.timeline.timeline:Timeline: Starting
WARNING:isobar.timeline.clock:Clock: Timer overflowed (late by 0.039s)
WARNING:isobar.timeline.clock:Clock: Timer overflowed (late by 0.280s)
INFO:isobar.io.midi.output:Opened MIDI output: IAC Driver Bus 1
INFO:isobar.timeline.timeline:Timeline: Scheduled new track (total tracks: 1)

INFO:isobar.timeline.timeline:Timeline: Track finished, removing from scheduler (total tracks: 0)
```

So the track is removed before I can even `update()` anything on it.

I can confirm that with:

```
In [3]: timeline.tracks
Out[3]: []
```

I can call update() on stream1 but nothing happens. When I try and unschedule the track I am told that the track is not scheduled.

Am I doing something wrong? Or is there some issue?

Thanks....

**Comment by loparcog** [comment]
It seems like you need to run `timeline.background()` after you schedule anything on it. Everything seems to work fine after that, but this is probably something that can be fixed around.
