### ISSUE TITLE
Generate documentation pages for each Pattern subclass

### ISSUE THREAD

**Issue by ideoforms** [ideoforms/isobar#35]

**Comment by loparcog** [comment]
We can use the following regex and `re.search` to repetitively pull up classes and their documentation in the code:

`class\s[\w():]+\s+"""((?!""").)*"""`

Using this gets us

```py
class PSequence(Pattern):
    """ Sequence: Sequence of values based on an array
        Takes an input list, and repeats the items in this list.

        >>> p = PSeq([ 1, 2, 3, 5 ])
        >>> p.nextn(10)
        [1, 2, 3, 5, 1, 2, 3, 5, 1, 2, 3, 5, 1, 2, 3, 5]
        """
```

Which can then be formatted as the following:

### PSequence

Sequence: Sequence of values based on an array Takes an input list, and repeats the items in this list.
>>> p = PSeq([ 1, 2, 3, 5 ]) >>> p.nextn(10) [1, 2, 3, 5, 1, 2, 3, 5, 1, 2, 3, 5, 1, 2, 3, 5]

The main point where I'm having issue is in how the code should be formatted (either using > indents or removing those and surrounding them with ``` blocks), and also how to deal with titles, since some documentation starts with the pattern name (like the above starting with `Sequence`) and others do not.

**Comment by loparcog** [comment]
There aren't too many instances of it, but when there are comments for init args, they look to be in the format of:

```py
Args:
            initial_value (float or int): Initial value
            step (float or int): Maximum value to increase or decrease by each step
            min (float or int): Minimum permitted value
            min (float or int): Maximum permitted value
```

Would this be the standard to stick to and work around or would you want to change the comment formatting before pushing the doc changes?

**Comment by ideoforms** [comment]
Happy to keep these as-is for now and address in a future change :)

**Comment by loparcog** [comment]
Got this working with the current args formatting and also made the index page push out to `library.md` to replace the file currently there. Main thing now would be adding all of this to the `nav` for MKDocs, where I would mainly want to check if we want to have all of these files in their own nav line or if we want to combine all of the markdown files into one for each python file.
