### ISSUE TITLE
Euclidean Algorithm with reversed arguments

### ISSUE THREAD

**Issue by debjan** [ideoforms/isobar#4]
Hi,

let me first thank you for making and sharing this package, and comment on [`isobar/pattern/sequence.py#L609`](https://github.com/ideoforms/isobar/blob/master/isobar/pattern/sequence.py#L609) where arguments seems reversed from initially suggested (i.e. http://cgm.cs.mcgill.ca/~godfried/publications/banff.pdf).
I thought to comment on this because also examples elsewhere refer to a function `E(k,n)`, where `k` denotes the number of one’s and `n` is the length of the sequence.

As yet another comment, I tried your package on Windows, and made the midi work after replacing `python-rtmidi` package with [`rtmidi-python`](https://pypi.python.org/pypi/rtmidi-python) (which works fine on Windows too) and then making some updates to `io/midi.py`, of course.

Cheers

**Comment by ideoforms** [comment]
Apologies for the slow response, fell behind somewhat on my package maintenance. Agreed that the ordering should be (ones, length) - have updated PEuclidean accordingly. Glad to hear you've had success with MIDI on Windows too. Thanks for the feedback, much appreciated.
