### ISSUE TITLE
iso.Key.nearest_note - upper bound issue

### ISSUE THREAD

**Issue by piotereks** [ideoforms/isobar#45]
Existing iso.Key.nearest_note is not considering (root note + 12) in proximity check. 
Example below shows that midi note 59 which is closest to note 60 iso.Key.nearest_note shows 57 instead
![image](https://user-images.githubusercontent.com/69604748/235510480-93d9f9f2-4eab-4385-b395-056cefafd5bc.png)

I can solve that already.

**Comment by ideoforms** [comment]
Resolved by #46
