### ISSUE TITLE
Restrict total time of a timeline

### ISSUE THREAD

**Issue by hay** [ideoforms/isobar#49]
Hey, thanks so much for making this library. I'm trying to incorporate it into a larger framework to make generative music, which is not using this library in real-time. For that reason, i'm trying to find a way to limit the amount of time a total timeline can take. For example, the [Steve Reich example](https://github.com/ideoforms/isobar/blob/master/examples/05.ex-piano-phase.py) by default loops infinitely, but i would really like to limit it to, say, three minutes.

I know i can add the `count` argument to the `schedule` method, but that means i need to add it to every single method call. Is there another way to force the timeline to stop after a specific amount of time, and still make it write / render the composition to a MIDI file as fast as possible?

**Comment by ideoforms** [comment]
Hey @hay, for this, I would recommend scheduling an `action` event that calls `timeline.clear()` with a `delay` corresponding to the time (in beats) at which you want to stop the generation. For example:

```
output = MidiFileOutputDevice("output.mid")
timeline = Timeline(MAX_CLOCK_RATE, output_device=output)
timeline.stop_when_done = True

timeline.schedule({
    "note": PSequence([36, 48, 60]),
})

timeline.schedule({
    "action": lambda: timeline.clear(),
}, delay=32)

timeline.run()
output.write()
```

Hope that helps!
