### ISSUE TITLE
Modifying events in an active timeline?

### ISSUE THREAD

**Issue by d-vyd** [ideoforms/isobar#55]
Hi! Thank you for this library! How might I modify events in an active timeline? For example, if I wanted to modify pitch, duration, and amplitude in realtime via MIDI CC? I've hastily combined some code from your examples to see if changing a global amplitude variable used when creating events might update those events after they were assigned to a timeline (shown below). That does not work--all the notes play at the same volume. What is the correct approach? Also, importing isobar produces the warning No module named 'link'. What might be causing that?

```
import isobar as iso

def process_message(message):
    global amplitude
    if message.control == 1:
        amplitude = message.value
    print(" - Received MIDI: %s" % message)

def main():
    global amplitude
    series = iso.PRange(60, 73, 1)
    timeline = iso.Timeline(tempo=120, output_device=midi_out)
    timeline.schedule({
        "note": series,
        "duration": 1,
        "amplitude": amplitude,
    })

    timeline.start()
    midi_in.callback = process_message

if __name__ == "__main__":
    outname = "loopMIDI Port 1 2"
    inname = "Midi Fighter Twister 0"
    midi_out = iso.MidiOutputDevice(device_name=outname,send_clock=True)
    midi_in = iso.MidiInputDevice(device_name=inname)
    amplitude = 64
    main()
    while True:
        pass
```

**Comment by ideoforms** [comment]
Hey @d-vyd, for MIDI control, I've recently been adding some pattern classes for this exact case. `PMIDIControl` generates the last-received value for the MIDI CC that you specify as its first parameter. Code [here](https://github.com/ideoforms/isobar/blob/master/isobar/pattern/midi.py); I'll add some proper documentation on this shortly.

So in your case, you could do:
```
timeline.schedule({
        "note": series,
        "duration": 1,
        # use the last-received value of MIDI CC 7 (or 8, using numbering from 1) 
        "amplitude": PMIDIControl(7),
    })
```
To use a MIDI device other than the default, set the environmental variable `ISOBAR_DEFAULT_MIDI_IN` to the name of your preferred MIDI device at the start of the script.

Re `No module named 'link'`: Oh dear, this looks like a bug from some development work I'm doing on integrating Ableton Link support. I'm not sure why the automated testing didn't catch it though. I'll get this fixed. What version are you using (+ from pypi or git clone), and how are you importing?

Thanks for the report!

**Comment by ideoforms** [comment]
I tracked down the `No module named 'link'` issue; it was just a warning that shouldn't have shown up. Now fixed. Thanks!

**Comment by d-vyd** [comment]
Thanks @ideoforms ! I started experimenting with my own code (outside of isobar) for this use case, player threads that read from a global cyclic integer clock and global MIDI controller values. However, since you address my use case within isobar, I'll definitely look at the code you referenced. Thanks again!
