### ISSUE TITLE
Trouble installing using pip3

### ISSUE THREAD

**Issue by raw-bit** [ideoforms/isobar#6]
Hi,

I'm getting the following error message when using pip3 install isobar-master.zip:

> Processing ./isobar-master.zip
> Collecting pyOSC>=0.3b0 (from isobar==0.0.1)
>   Downloading pyOSC-0.3.5b-5294.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-ptkkgifk/pyOSC/setup.py", line 5, in <module>
>         import OSC
>       File "/tmp/pip-build-ptkkgifk/pyOSC/OSC.py", line 735
>         binary = struct.pack('>ll', 0L, 1L)
>                                      ^
>     SyntaxError: invalid syntax
> 
> ```
> ----------------------------------------
> ```
> 
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ptkkgifk/pyOSC/

Thanks for taking a look. Hope it's not me.

**Comment by ideoforms** [comment]
This looks to be an issue with the external pyOSC dependency, which unfortunately is not compatible with Python 3, and hasn't been maintained for several years. I'll look into porting isobar to use liblo or similar.

Right now, the only workaround I could suggest is to switch to using Python 2, if that's an option for you. Apologies!

**Comment by vortextemporum** [comment]
Hi ideoforms,

is there any update with porting? I'd be really glad to be able to use it with Python 3!

**Comment by ideoforms** [comment]
@vortextemporum Yes, glad to say I've now updated isobar to be Python 3 compatible. Thanks for your patience :-)
